# empytdir is usually used in pods with multiple containers

apiVersion: v1
kind: Pod
metadata:
  name: example-emptydir
spec:

  volumes:
  - name: vol1
    emptyDir: {}

  containers:
  - name: c1
    image: alpine
    command: [ "ping", "127.0.0.1" ]
    volumeMounts:
    - name: vol1
      mountPath: /data

  - name: c2
    image: nginx
    volumeMounts:
    - name: vol1
      mountPath: /data-nginx

