# this pod is using a Secret named my-secret
# manually created with
# kubectl create secret generic my-secret --from-literal=key1=supersecret


apiVersion: v1
kind: Pod
metadata:
  name: secret-example
spec:
  containers:
    - name: alping
      image: alpine:3.11
      command: [ "ping", "127.0.0.1" ]
      env:
        - name: VAR1
          valueFrom: 
            secretKeyRef:
              name: my-secret
              key: key1

