apiVersion: apps/v1
kind: Deployment
metadata:
 name: deploy-liveness
spec:
 replicas: 1
 selector:
   matchLabels:
     app: deploy-liveness
 template:
   metadata:
    labels:
      app: deploy-liveness
   spec:
     containers:
     - name: c1
       image: vvang/dummy:x86
       livenessProbe:
         initialDelaySeconds: 10
         periodSeconds: 3
         httpGet:
           path: /
           port: 8080

