
# see https://github.com/bitnami/charts/tree/master/bitnami/postgresql/

architecture: replication

auth:
  postgresPassword: '123456'

primary:
  persistence:
    size: 1Gi
  resources:
    requests:
      memory: 100Mi
      cpu: 10m
readReplicas:
  count: 1
  persistence:
    size: 1Gi
  resources:
    requests:
      memory: 100Mi
      cpu: 10m

